In [1]:
import pandas as pd 
data=pd.read_csv(r"C:\Users\HP\Downloads\Mobile_data.csv")
data.head(10)

,battery_power,clock_speed,fc,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,price_range
0,842,2.2,1,7,0.6,188,2,2,20,756,2549,9,7,19,1
1,1021,0.5,0,53,0.7,136,3,6,905,1988,2631,17,3,7,2
2,563,0.5,2,41,0.9,145,5,6,1263,1716,2603,11,2,9,2
3,615,2.5,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,2
4,1821,1.2,13,44,0.6,141,2,14,1208,1212,1411,8,2,15,1
5,1859,0.5,3,22,0.7,164,1,7,1004,1654,1067,17,1,10,1
6,1821,1.7,4,10,0.8,139,8,10,381,1018,3220,13,8,18,3
7,1954,0.5,0,24,0.8,187,4,0,512,1149,700,16,3,5,0
8,1445,0.5,0,53,0.7,174,7,14,386,836,1099,17,1,20,0
9,509,0.6,2,9,0.1,93,5,15,1137,1224,513,19,10,12,0

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   clock_speed    2000 non-null   float64
 2   fc             2000 non-null   int64
 3   int_memory     2000 non-null   int64
 4   m_dep          2000 non-null   float64
 5   mobile_wt      2000 non-null   int64
 6   n_cores        2000 non-null   int64
 7   pc             2000 non-null   int64
 8   px_height      2000 non-null   int64
 9   px_width       2000 non-null   int64
 10  ram            2000 non-null   int64
 11  sc_h           2000 non-null   int64
 12  sc_w           2000 non-null   int64
 13  talk_time      2000 non-null   int64
 14  price_range    2000 non-null   int64
dtypes: float64(2), int64(13)
memory usage: 234.5 KB

In [5]:
X = data.drop(['price_range'],axis=1)
y = data['price_range']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=0)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(X_train, y_train)

y_pred=neigh.predict(X_test)

In [7]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))

[[145   6   0   0]
 [ 10 117   8   0]
 [  0   8 126  17]
 [  0   0  15 148]]

In [8]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95       151
           1       0.89      0.87      0.88       135
           2       0.85      0.83      0.84       151
           3       0.90      0.91      0.90       163

    accuracy                           0.89       600
   macro avg       0.89      0.89      0.89       600
weighted avg       0.89      0.89      0.89       600

In [10]:
print(accuracy_score(y_test,y_pred))

0.8933333333333333